# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4exfDHQp8v4vnhSMUMaKkwwAKaTb9gw

### BUILT IN FUNCTIONS : **list** **bold text**
"""

arr1 = [1,2,3,4,5]
arr2 = [3,5,6,1]
print("Lenght of arr1 : ",len(arr1))

print("maximum : ", max(arr2))

print("minimum : " ,min(arr1))

tup = ('a','b','c')
print("complete list is :",list(tup))

arr1.append('mustafa')
print("after append list is : " , arr1)

arr1.count('mustafa')

print("Return index of mustafa : ",arr1.index('mustafa'))

arr1.insert(2,'arsalan')
print("after inserting :",arr1)

print(arr1.pop())
print("after popping last element : ",arr1)

arr1.remove(4)

print("after removing selected index : ",arr1)


arr1.reverse()
print("after reverse : ",arr1)

arr2.reverse()
print(arr2)

arr2.sort()
print("after sorting : ",arr2)

"""# ***TUPLESS***"""

tup1 = (1,2,3,4,9)
print("lenght of tuple : ",len(tup1))
print("maximum : ", max(tup1))
print("minimum : ",min(tup1))

arr = ['a','b','c']
tup = tuple(arr)
print("after conversion : ",tup)

"""# **DICTIONARY** """

dicts = {'a':"apple",'b':2,'c':2.2,'d':{'unique':28}}
print("Dictionary elements : ",dicts)
dicts2 = {'a':"apple",'b':2,'c':2.2,'d':{'unique':28},'u':"mustafa"}
#print(cmp(dicts,dicts2))
print("Length of dictionary : ",len(dicts2))
print("String conversion :",str(dicts))
print("Type : ",type(dicts2))
print("Clear : ",dicts.clear())
print(str(dicts))
temp = dicts2.copy()
print("copy of dictionary : ",temp)

print(temp.get('a'))

print(dicts2.items())

print("Values are : ",dicts2.values())

print("Keys are : ",dicts2.keys())

dicts.update({'m':'mustafa'})
print("after update dictionary : ",dicts)

#1. Store the names of a few of your friends in a list called names.
#Print each person’s name by accessing each element in the list, one at a time.
print("\t\tAnswer 1 ")
name = ["Abdullah","Mehran","Taha","Arsalan"]
for i in name:
  print(i)

#2. If you could invite anyone, living or deceased, to dinner, who would you invi
#Make a list that includes at least three people you’d like to invite to dinner.
#Then use your list to print a message to each person, inviting them to dinner.
print("\t\tAnswer 2 ")
invitedPerson = ["Abdullah","Mehran","Taha","Arsalan"]
for i in invitedPerson:
  print(i,", you are invited at my home." )

#3. Changing Guest List: You just heard that one of your guests can’t make the din
# so you need to send out a new set of invitations.
# You’ll have to think of someone else to invite.
#● Modify your list, replacing the name of the guest who can’t make it with the n
#● Print a second set of invitation messages, one for each person who is still in
print("\t\tAnswer 3 ")
invitedPerson = ["Abdullah","Mehran","Taha","Arsalan"]
invitedPerson[invitedPerson.index("Arsalan")] = "Osama"
for i in invitedPerson:
  print(i, ", you are invited at my home" )

# Create a Class “Employee”, it’s a common base class for all the employees. Then
# initialize employee’s parameters like empName and salary and create functions like
# displayCount() containing the total number of employees in your knowledge base and
# displayEmployee() containing empName and their salary.
print("\t\tAnswer 4 ")
class Employee:
    "t’s a common base class for all the employees"
    totalEmployee = 0
    def __init__(myobject,empName,salary ):
        myobject.empName = empName
        myobject.salary = salary
        Employee.totalEmployee += 1
    
    def displayCount(myobject):
        print("Total Employees are: ",Employee.totalEmployee)
        
    def displayEmployee(myobject):
        print(myobject.empName,myobject.salary)

first = Employee("Mustafa",2000000)
second = Employee("ali",30000)
third = Employee("abdullah",28759)
fourth = Employee("mehran",2925627943)
fifth = Employee("taha",22387647238)
first.displayCount()
first.displayEmployee()
second.displayEmployee()
third.displayEmployee()   
fourth.displayEmployee()
fifth.displayEmployee()